name: sparse_als
channels:
  - conda-forge
dependencies:
  - python>=3.7
  - numba
  - numpy
  - scipy
  - joblib
  - matplotlib
  - scikit-learn
  - tensap
  - tqdm
  - loguru
  - rich
  - loguru
  - colored
  - ipython
  - flake8
  - flake8-docstrings
  - mypy
  - black
  - isort
  - memory_profiler
  - snakeviz
  - pip:
    - deal[all]
    - sparseqr